### ISSUE TITLE
Class abolished when piece is moved??

### ISSUE THREAD

**Issue by srb95** [sukritchhabra/chessGame-cs451#15]
I see that class goes from class="white pawn glyphicon glyphicon-pawn unmoved" to just class when a piece is moved. Why is this? I need it to stay so I can toggle an unmoved class to see if its the first move or not for my move validation portion

**Comment by sukritchhabra** [comment]
So, what is happening is that the `glyphicon glyphicon-pawn` is what is drawing the piece in the cell.
I am also giving classes `white`,`pawn` and `unmoved` to be able to search by type/property instead of id's. 

When a piece is moved the cell it is moved from becomes empty, therefore these characteristics are not required by that cell, hence these are being removed.

**Comment by srb95** [comment]
I don't see a class of `unmoved` on there and need that for the pawns for move validation to see if it is the first move so I can allow them to move 2 spaces. Can you please add this to the pawns initially, and once the pawns are moved, delete the class `unmoved`? Thanks
